### ISSUE TITLE
An option to show week numbers

### ISSUE THREAD

**Issue by Roye7777777** [qodesmith/datepicker#100]
Hello! I appreciate the datepicker and it's being used happily. I wonder, as a new feature request, will it in the future be possible to toggle numbers of the week on the left side? Thanks!

**Comment by qodesmith** [comment]
Sorry for the delay. I just saw your example. I think a feature like this would take a substantial effort - there's style and layout changes which would affect how the JS processes creating the calendar as well. I think I'll hold off for now but perhaps we can revisit this in the future.
