### ISSUE TITLE
Supporting strict mode

### ISSUE THREAD

**Issue by james-em** [qodesmith/datepicker#101]
Hi,

When using this library in strict mode, I am getting this error with uglify:

```
In strict mode code, functions can only be declared at top level or immediately within another function..
```

It would be great if the library could follow these specs :)

Thank you
James

**Comment by qodesmith** [comment]
I use Webpack to bundle the entire library into a single function - and the code is already uglified with Terser, so I'm not sure how anything here is breaking specs. Is there anything else in the message? Otherwise I'm not sure it's Datepicker causing the issue.

**Comment by qodesmith** [comment]
A quick google search shows that this error comes up when functions are declared in for loops or in conditional statements. I was able to find a single instance where [I declared a function in an if statement](https://github.com/qodesmith/datepicker/blob/a88a209e784da23e1bbffb0f896e6c764591c287/src/datepicker.js#L615-L618). I'll put up a change now :)

**Comment by qodesmith** [comment]
Ok, just pushed `5.16.0`. All fixed.

**Comment by james-em** [comment]
@qodesmith 

I forgot to say thank you ! It fixed the issue with uglify ! :)
