### ISSUE TITLE
Set startDay:1 and noWeekends: true will disable monday and sunday

### ISSUE THREAD

**Issue by AureliusSlawinski** [qodesmith/datepicker#107]
If setting these options:

startDay:1
noWeekends: true

Will disable monday and sunday (instead of saturday and sunday).

![grafik](https://user-images.githubusercontent.com/9914122/92740737-478be200-f37e-11ea-9e46-ba317004aa2d.png)

**Comment by axelschelfhout** [comment]
I have the same issue. For now I "solved" it with
`disabler: date => date.getDay() === 6 || date.getDay() === 0, // Disable weekends`

**Comment by qodesmith** [comment]
Sorry for the delay, looking into this now...

**Comment by qodesmith** [comment]
Fixed!
