### ISSUE TITLE
Jalali Calendar

### ISSUE THREAD

**Issue by MR-Mostafa** [qodesmith/datepicker#112]
Hello
Is any way to your datepicker support jalali calendar (Persian Calendar)?
For logic difference between these dates(jalali & gregorian) you can use: [Persian Date](http://babakhani.github.io/PersianWebToolkit/doc/persian-date/) OR [jalaali-js](https://github.com/jalaali/jalaali-js)
Thanks

**Comment by qodesmith** [comment]
@MR-Mostafa Hey, I know this is an older issue, but I'm just getting back in the swing of things. It looks like it would take a substantial effort to support this. I might need to think about implementing a plugin system that would allow for custom calculation of days in the calendar, year, and start day.
