### ISSUE TITLE
Month not updating on Win10

### ISSUE THREAD

**Issue by dgk816** [qodesmith/datepicker#113]
Hello,

I'm not sure this is a real issue.

I'm used nw.js to write a small calendar app that is always present in the upper right of my desktop.  I initially wrote it using a Debian 10.8 virtual machine running in Virtualbox, then moved it to my Windows 10 desktop.

In the picture, the calendar on the left is the Debian VM showing the correct month.  The right one is the Win10 version.  These are on the same computer and both were running when the month changed.  You can see the Linux version updated to March but the Windows version stayed on February.

I realize datepicker is meant to be, well, a date picker, and not a continuously running calander.  I just thought it was curious how the behavior is slightly different between the operating systems. 

This is how I update the date:
`
var std = setInterval( setthedate, 5000);

....some other code....

function setthedate() {
    picker.setDate( new Date() );
}
`
Thanks for your time.

![image](https://user-images.githubusercontent.com/79928809/109682584-2beee080-7b44-11eb-9274-700bb5a09985.png)

**Comment by dgk816** [comment]
Some more info,

As soon as I clicked somewhere on the calendar, the month updated correctly.

As I said earlier, I don't think this is a problem, just an oddity.

**Comment by qodesmith** [comment]
@dgk816 Hey, I know this is old, but I think it's fascinating that you used this for a desktop widget! Did you ever figure out what the issue was? One thought would be if the different operating systems are using a different timezone for whatever reason.

**Comment by qodesmith** [comment]
Question for you - when you expected the calendar to update to March, this update was in response to what? Did you wait till midnight to see the change or something? I get that you have a setInterval running every 5 seconds, so I'm just curious if this was in response to a click event or something else.
