### ISSUE TITLE
Allow setting custom location

### ISSUE THREAD

**Issue by YZirkind** [qodesmith/datepicker#116]
Currently the [`position`](https://github.com/qodesmith/datepicker#position) option only allows setting the position directly relative to the associated input, or fixed to the center of the screen.

It would be nice to have the ability to set a custom fixed position anywhere on the screen.  My use case is that I have set the inputs to be hidden, so the picker only shows up in the top left corner of the screen.

**Comment by qodesmith** [comment]
Check [this fiddle](https://jsfiddle.net/theqodesmith/tgn7b23o/3/) out to see how you can position the calendar fixed on the page. You mentioned you were hiding the input so I used a regular <div> instead.

**Comment by YZirkind** [comment]
Thanks! I tried it using a `<div>` as in your fiddle and it worked, so I really didn't need to use hidden inputs for it.
