### ISSUE TITLE
Days are not the same like in the normally Calendar

### ISSUE THREAD

**Issue by kriss145** [qodesmith/datepicker#118]
I've implemented this plugin to my project and I see that days are not the same like in the Calendar.

Example: 10.06.2021 in the plugin is Friday but should be Thursday.

It's look like all days are moved +1 day.

Could u help me quickly? 

Thanks!

**Comment by qodesmith** [comment]
@kriss145 Can you spell out the date explicitly so I know exactly which date to check? Are you referring to October 6th, 2021?

**Comment by qodesmith** [comment]
I just realized today is 6/10/2021 which is what you're probably referring too, haha. The calendar seems to work fine for me, correctly showing today as Thursday. Are you using the latest version, 5.18? You can see it working in [this fiddle](https://jsfiddle.net/theqodesmith/pe75vk1w/) which is explicitly using v5.18.
