### ISSUE TITLE
Namespace CSS classnames

### ISSUE THREAD

**Issue by drlovebaum** [qodesmith/datepicker#12]
Nothing broken, but the class names are so common ['controls', 'datepicker'] they really need to be namespaced to fit in universally w/other peoples' work while not breaking visually.

Recommend:  'qds-datepicker', 'qds-controls', etc.

**Comment by qodesmith** [comment]
Excellent point. I just prefixed all the classes with `qs-`. Also found another bug or two as a result of going through the code, so thank you!
