### ISSUE TITLE
date range

### ISSUE THREAD

**Issue by bsastregx** [qodesmith/datepicker#120]
Hi!
First of all, thanks so much for suchn an amazing plugin!
I am using a date range with the following **min** and **max** dates:

**minDate** = "1000, 1, 1";
**maxDate** = "3000, 1, 1";

When using the date range, for the ".start" date picker the last available date is today, and for the ".end" date picker the first available date is today. In other words, I can not select a range in that is completely on the past, or a range that is completely in the future.

I have recorded a video for better understanding:
https://www.awesomescreenshot.com/video/5146180?key=1693d3df89d64473c021635258a8d2a8

**Comment by qodesmith** [comment]
Can you post a code snippet of how you instantiate the two datepickers?

**Comment by bsastregx** [comment]
Sure: https://codepen.io/brsastregx/pen/QWgdrxm?editors=1010

**Comment by qodesmith** [comment]
After looking at the code, it looks like both pickers in the range have the same value for `dateSelected`. Remove both of them and let me know how it works.

**Comment by bsastregx** [comment]
That worked! Thanks so muchhhh!!!
