### ISSUE TITLE
datepicker not working in iOS

### ISSUE THREAD

**Issue by mrispoli24** [qodesmith/datepicker#13]
The datepicker is working great for me everywhere except on iOS (safari and chrome). Whenever I try to click on a date it does not register and will not dismiss once open on the input.

**Comment by qodesmith** [comment]
Hmmm... I'll look into it hopefully tonight. I'll circle back as soon as I have a fix.

**Comment by mrispoli24** [comment]
@qodesmith 

I have the solution but it makes no sense to me why this worked exactly:

```
const picker = datepicker(document.querySelector('#moveInDate'), {
    formatter: function(el, date) {
      el.setAttribute('placeholder', '');
      el.setAttribute('value', date.toISOString().slice(0,10));
    },
      onSelect: function(instance) {
      // Show which date was selected.
      console.log(instance.dateSelected);
    },
    onShow: function(instance) {
      console.log('Calendar showing.');
      $('.square').on('click', function(e){});
      $('.arrow').on('click', function(e){});
    },
    onMonthChange: function(instance) {
      // Show the month of the selected date.
      console.log(instance.currentMonthName);
      $('.square').on('click', function(e){});
      $('.arrow').on('click', function(e){});
    },
      disableMobile: false,
    });
```

So by adding these click events on the show and month change events it starts working on mobile. I'm not really sure why and I'm thinking maybe Safari/Chrome have a different way of handling event propagation for touch screens that requires this. I'm going to see if I can figure out why exactly this worked but right now it appears rather magical.

**Comment by ravibhoraniya** [comment]
hello, 
how to particular single date disable plz give me a idea.

thank you.

**Comment by qodesmith** [comment]
Hey @ravibhoraniya. Sorry for the delayed response. Not sure I understand your question. What exactly are you looking to do?

**Comment by qodesmith** [comment]
@mrispoli24 I know it's been a while. I've updated the code and removed a mutation observer that was responsible for showing & hiding the calendar. If you can, try the latest version and see if that solves the issue.

**Comment by mbruggenwirth** [comment]
I use the latest version (2.1.5) but I have a problem with de selection of a date on IOS.

**Comment by RakeshGowdaM** [comment]
Hi, ngb date picker is working fine on mobile and desktop. Only on ipad it's not working. As soon as I click on month or year the calander is getting close. Not able to select the date on ipad tab

**Comment by payalpedkar** [comment]
@RakeshGowdaM  
Hi I am facing same problem. 
Any soultion?

**Comment by qodesmith** [comment]
Is this still a problem with the latest version - 5.0.2?
