### ISSUE TITLE
Datepicker localization 

### ISSUE THREAD

**Issue by vaneatka** [qodesmith/datepicker#136]
Is there a way to fully localize the datepicker?

As per docs, there is possibility to format the output

const picker = datepicker('.some-input', {
  formatter: (input, date, instance) => {
    const value = date.toLocaleDateString()
    input.value = value // => '1/1/2099'
  }
})

customDays,
customMonths,
etc....

but what if I there is no a limited number of languages to translate
![image](https://user-images.githubusercontent.com/37835435/227873469-102bf696-20b0-4005-8e14-7fefa07b7d27.png)

mayme it is worth to add a per/datepicker config option to localize it

**Comment by vaneatka** [comment]
`      customMonths: (() => [...Array(12).keys()].map(index => new Date(0, index).toLocaleString(navigator.language, { month: "long" })))(),
      customDays: (() => {
        function getWeekDates(){
          const dates = [new Date()]; // today
          const curr = new Date();
          const remDaysCount = 7-curr.getDay();
          for(let i=1; i<= remDaysCount; i++){
            const nextDate = curr.setDate(curr.getDate()+1);
            dates.push(new Date(nextDate));
          }
          return dates;
        }

        const days = [...getWeekDates().map(date => date.toLocaleString(navigator.language, { weekday: "short" }))];
        // the element shift is needed because of the datepicker expects first day of the week to be Sunday
        days.unshift(days.pop()!)
        return days;
      })(),
      customOverlayMonths: (() => [...Array(12).keys()].map(index => new Date(0, index).toLocaleString(navigator.language, { month: "short" })))()`

this is how it might be implemented

**Comment by qodesmith** [comment]
I'm not sure I understand. What part of the calendar are you trying to localize that can't currently be customized?

**Comment by qodesmith** [comment]
I think [this thread](https://github.com/qodesmith/datepicker/issues/137#issuecomment-1497349272) is relevant to your localization concerns. New features are coming up in the next major version of datepicker.

**Comment by vaneatka** [comment]
> I'm not sure I understand. What part of the calendar are you trying to localize that can't currently be customized?

I had to localize all the places that are translatable.

So I was expecting to have an option: ex 
{
...options,
localizedPartsOfDatepicker: ['daysOfTHeWeek', "monthsEverywhere", etc etc etc]
}

this would do the work mentioned in the code snippet provided in this thred itself.

**Comment by qodesmith** [comment]
@vaneatka Like I mentioned in the last comment, I've got some upcoming features that should cover all areas of the calendar for localization:
* Calendar day numbers (this is new)
* Calendar year (this is new)
* Overlay year input value (this is new)
* Month names (this already exists)
* Overlay month names (this already exists)
* Overlay input placeholder (this already exists)
* Overlay submit button (this already exists)
* Sanitizing the input field's value (this already exists)

**Comment by bemes9226** [comment]
Is it fix this localisation
