### ISSUE TITLE
Strange bug with Angular when re-setting minDate, any tips?

### ISSUE THREAD

**Issue by jvlobo** [qodesmith/datepicker#138]
Hello. 

We are using this library in an Angular application and I found a strange bug that I'm not sure why it is happening.
I recorded a quick video showing the issue:

https://user-images.githubusercontent.com/5671420/229826521-a5521202-1f4b-4c59-8e2a-b213d0bcfe64.mov

You can see the small piece of code on the left in the editor. Basically I have a web component `calendar` that uses this library. I can send props to this component like minDate, maxDate etc.
So, in this case, I initialize the calendar with:

```
datePickerOptions = {
    minDate: new Date(2021, 1, 1),
    maxDate: new Date(2021, 12, 31),
    initialDate: new Date(2021, 6, 1),
  };
 ```
 
 And then, when a date is selected, I change the `minDate` to another date, as shown.
 When this is done, what it happens is that the calendar becomes "unresponsive", so when I open it and click somewhere it closes.
 
 After some investigation, I realized that, when the minDate (or maxDate or other property) is changed dynamically, the `qs-datepicker-container` element is re-render, but in the wrong location, as you can see in the video.
 
 Any idea why this is happening? Any tips on what I can look for in the library's code? I'm happy to do a PR with a fix, but I'm not too sure where to investigate for this.
 
 By the way, I know the library has the `setMin`, `setMax` methods to set these parameters, but as we are using this library through a web-component, the parameters can be changed dynamically and we would like to, at least, keep the calendar working properly is this happens.
 
 Thank you!

**Comment by jvlobo** [comment]
I'm using StencilJS for the components library we have.
So I'm calling the `datepicker(...)` function inside the `componentDidLoad()` lifecycle event from [StencilJS](https://stenciljs.com/docs/component-lifecycle#componentdidload).

I've been debugging and it seemed like the `createInstance()` function from the datepicker was not being called again when this strange behaviour was happening.

I guess Angular "re-renders" the component somehow when a prop is changed. And this is messing up things somehow 🤔

I've been able to fix it by using a datepicker.remove() and initializing it again on the `componentDidUpdate()` lifecycle event. Not sure if it is the best option, but it works for now.

I believe something else could be done on the library to prevent this, but I have no idea for now.

**Comment by qodesmith** [comment]
Yea, I had a suspicion that this had to do with a component unmounting but datepicker not being re-initialized. I'm not familiar with StencilJS or Angular, but I'm familiar with lifecycle methods in general (from React). If you're initializing datepicker in the `componentDidLoad` lifecycle, I'm guessing there's a `componentDidUnmount` lifecycle or equivalent. You'll want to make sure `picker.remove()` is called there. But this should only be necessary if `componentDidLoad` will be called multiple times. It would be best to initialize datepicker in a lifecycle that is only called once.

Just in case it helps, I'm currently re-writing the entire library (most of the options will stay the same) in the [2022-rewrite branch](https://github.com/qodesmith/datepicker/tree/2022-rewrite). In that branch I have a [sandbox React application](https://github.com/qodesmith/datepicker/tree/2022-rewrite/sandbox) I'm using to test out datepicker as I develop. I ran into some of the same issues you're facing when trying to get datepicker working with React (it wasn't designed with React in mind or any framework for that matter - datepicker interacts directly with the DOM which these frameworks don't like). I needed to take into account lifecycles and call `picker.remove()` accordingly. You can see that [here](https://github.com/qodesmith/datepicker/blob/47ff9cb2ffe866285775e889c66617cd07c44e43/sandbox/useDatepicker.tsx#L48), where I implemented this functionality in a custom hook. I [initialize datepicker in React's mount lifecycle](https://github.com/qodesmith/datepicker/blob/47ff9cb2ffe866285775e889c66617cd07c44e43/sandbox/useDatepicker.tsx#L44) and [call `picker.remove()` in React's unmount lifecycle](https://github.com/qodesmith/datepicker/blob/47ff9cb2ffe866285775e889c66617cd07c44e43/sandbox/useDatepicker.tsx#L48).
