### ISSUE TITLE
Not Work "npm i --save-dev @types/js-datepicker"

### ISSUE THREAD

**Issue by sa-tsuki** [qodesmith/datepicker#139]
code E404
Not Found - GET https://registry.npmjs.org/@types%2fjs-datepicker
'@types/js-datepicker@*' is not in this registry.

**Comment by littlecrome** [comment]
Hi, so how do you fix the following error please?
<img width="1034" alt="image" src="https://github.com/qodesmith/datepicker/assets/4664838/65122447-b36e-415c-ac76-e510b0660378">
Even though you have declared it, the code is still looking for it.

Thanks.
