### ISSUE TITLE
submit.classList[addRemove] throws error

### ISSUE THREAD

**Issue by pryley** [qodesmith/datepicker#14]
https://github.com/qodesmith/datepicker/blob/master/datepicker.js#L661
```js
const addRemove = badDate ? 'qs-add' : 'qs-remove';
```

Should be:

```js
const addRemove = badDate ? 'add' : 'remove';
```

**Comment by qodesmith** [comment]
Thanks for catching this! Just fixed it. This was a result of me renaming all classes to `qs-*` to avoid conflicts with common names and other libraries, etc. Overlooked this one.
