### ISSUE TITLE
When entering a year it jumps right through and sends a submit event

### ISSUE THREAD

**Issue by dionmes** [qodesmith/datepicker#15]
Hi,

I really love your datepicker. I tried a lot of them and either they are to bloated or they don't fit in my garbage css styles. This one is great, fits in real nice without hassle.

Though I have an issue, when I enter the year and press return it dismisses the dialog and submits the form. Tried to do a event.preventdefault onHide. But that didn't help. 

Regards,
Dion

**Comment by qodesmith** [comment]
Can you share the relevant portion of your code? Let me see the html as well. When hitting return after entering a year, just the year dialog is removed. The calendar should still be visible.

**Comment by dionmes** [comment]
Sure. 
This is the call I make for attaching to the dom element:
Its all rendered via a php blade template so you see some blade placeholders between double brackets.
```
        const picker = datepicker('#eligo-birthdate-input',
            {formatter: function(el, date) { el.value = date.toLocaleDateString();},
            maxDate: new Date(),
            startDate: new Date('{{Auth::user()->User_info->birthdate->format('Y-m-d')}}')
        });

```

The relevant HTML look like this:

```
        <form id='details-form' name='details-form' method='POST' action='' accept-charset='UTF-8'>
                <input name='birthdate' type='text' id='eligo-birthdate-input' placeholder='{{trans('views.date_format')}}' ><br><br>
            <br>
            <input type='submit' value='{{trans("views.submit")}}'>
        </form>
```

**Comment by qodesmith** [comment]
Thanks for the code. I was able to reproduce the same behavior. The issue was in `datepicker`'s code I was using a `keyup` listener. I've changed that to `keydown` along with `e.stopPropagation()` on the enter key. The form won't auto-submit now. Good catch!

**Comment by dionmes** [comment]
Awesome. Thx m8!
