### ISSUE TITLE
First day of the week

### ISSUE THREAD

**Issue by liinavaker** [qodesmith/datepicker#20]
Hi! Thanks for the great plugin!

I can't seem to find a way to set Monday as the first day of the week. Is it possible?

**Comment by liinavaker** [comment]
Right now I got the desired result by changing the code in row 334 from
`const copy = new Date(new Date(date).setDate(1));`
to 
`const copy = new Date(new Date(date).setDate(0));`

Also changed the order of corresponding strings in days array.

I think it would be a useful feature to add as an option.

**Comment by qodesmith** [comment]
@liinavaker Thanks for pointing this out! Hadn't thought of this as an option before. Looking into it now...

**Comment by qodesmith** [comment]
@liinavaker Aaaaaaaand we're live! New `startDay` option added. An example:

```javascript
const picker = datepicker('#date', {
  startDay: 1 // Monday is the 1st day of the week now.
});
```

0 = Sunday
1 = Monday
2 = Tuesday
etc...

Thanks for the feature idea!
