### ISSUE TITLE
Esc key switches calendar view to "Year Navigation" and vice versa

### ISSUE THREAD

**Issue by renansan** [qodesmith/datepicker#24]

**Comment by qodesmith** [comment]
@renansan Just noticed this now as well. The intended behavior was to allow the user to press the esc key when the "year navigation" portion was open, behaving synonymous to "cancel". But I see that it triggers when the calendar is in view. Working on a fix now.

**Comment by qodesmith** [comment]
Fixed!  Now the esc only toggles the year overlay when it's open.
