### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by Pixelrobin** [qodesmith/datepicker#25]
I don't see a license listed anywhere, is that on purpose?

**Comment by qodesmith** [comment]
In the `package.json` the license is listed as `ISC` but I'm pretty sure that's just the default. In any case, nothing was omitted on purpose. This library is free to use however you want. No if's, and's, or but's about it! Free free free. I should probably create a license section in the readme soon just to avoid any confusion.

**Comment by Pixelrobin** [comment]
I brought it up because it appears that repositories without explicit licenses are [considered to be the author's sole property](https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github). Also, the ISC license is functionally identical to MIT, both of which are probably what you're looking for if you want it "free".

**Comment by qodesmith** [comment]
@Pixelrobin Ahhh, I didn't know that. Thanks for the heads up. Yea, I never intended for this to be exclusive material. I'll update the readme. Thanks again!
