### ISSUE TITLE
Multiple Define error

### ISSUE THREAD

**Issue by wspresto** [qodesmith/datepicker#26]
When using this library with another require style library such as dojo, i know.. forgive me, defining the library after or following the dojo library causes a multiple define error to be thrown.

In your typical index.html file:
src="dojo"
src="js-datepicker"

ERROR

Reversing the order so that the datepicker is first resolves the issues.

**Comment by qodesmith** [comment]
@wspresto I gotta be honest, I'll have to claim ignorance on this one. Not very familiar with the order sensitivity of require style libraries. Have you discovered a reason for things working when datepicker is required first?

The code at the top of the unminified code looks like this:
```javascript
(function(root, returnDatepicker) {
  if (typeof exports === 'object') return module.exports = returnDatepicker();
  if (typeof define === 'function' && define.amd) return define(function() {return returnDatepicker()});
  return root.datepicker = returnDatepicker();
})(this, function() {
  ...
})
```

It's basically checking to see which object to attach the datepicker function to. In the browser, that's `window`. Node, that's `module.exports`. In the require world, maybe I'm doing it wrong?
Could it be the whole `typeof define === 'function' && define.amd` line?
