### ISSUE TITLE
Add feature "dateDisabled"

### ISSUE THREAD

**Issue by webestet** [qodesmith/datepicker#27]
Hello. Thanks for your package.

But, I can't send date array, which `disable` this date. For example I want to exclude 11 April and 13 June. If I will can to use options
`dateDisabled: [
  new Date(2018, 3, 11),
  new Date(2018, 5, 13)
]` and this date switch to `qs-disabled`, I will enjoy :+1: )

**Comment by qodesmith** [comment]
@webestet Good idea. Hadn't thought of that before. Let me look into it...

**Comment by qodesmith** [comment]
@webestet Version 3 published! You can now supply an array of dates to be disabled in the `disabledDates` option.

**Comment by webestet** [comment]
Thanks)
