### ISSUE TITLE
datepicker + webpack

### ISSUE THREAD

**Issue by jpcmf** [qodesmith/datepicker#28]
I'm trying to use the plugin with webpack. The datepicker is loading in vendors.js and in app.js I call the datepicker but i'm getting this error `datepicker is not defined`. Any help?

**Comment by jpcmf** [comment]
Yes, check https://github.com/jpcmf/JPCars-JavaScript

**Comment by qodesmith** [comment]
I noticed what you were doing for jQuery and I wonder if this is needed for the datepicker also:

```javascript
plugins.push(new webpack.ProvidePlugin({
  datepicker: 'js-datepicker/datepicker.min.js'
}));
```

Try this and let know if this works.

**Comment by jpcmf** [comment]
I was adding the plugin in the wrong place:
```
module.exports = {
  entry: {
    app: './src/js/app.js',
    vendor: ['jquery', 'bootstrap', 'js-datepicker']
  },
```
Like you said, the right place is adding in the ProvidePlugin:
```
plugins.push(new webpack.ProvidePlugin({
  '$': 'jquery/dist/jquery.js',
  'jQuery': 'jquery/dist/jquery.js',
  'datepicker': 'js-datepicker/datepicker.min.js'
}));
```
It's working @qodesmith
Thank you

ps. There's a way to add only the year?
