### ISSUE TITLE
Minimal example does not work

### ISSUE THREAD

**Issue by Lambo232** [qodesmith/datepicker#30]
The minimal example does not work.  It requires a dateSelected.
The minimal example is:
`var picker = datepicker('#dp', {dateSelected: new Date()});`

**Comment by qodesmith** [comment]
@Lambo232 Excellent catch. You shouldn't have to pass in any options at all for the minimal example. I'm looking into it right now.

**Comment by qodesmith** [comment]
@Lambo232 Fixed! You can now use the minimal example like so:

```javascript
var picker = datepicker('#dp');
```
