### ISSUE TITLE
Feature: Possibility to disable year overlay

### ISSUE THREAD

**Issue by nkovacic** [qodesmith/datepicker#35]
Would be a great feature if you could disable the year overlay using a simple boolean in options.
Great work on the picker btw, its really lightweight and can be used in other frameworks :)

**Comment by qodesmith** [comment]
@nkovacic  I like this idea! I'll implement it and let you know when it's done.

**Comment by qodesmith** [comment]
@nkovacic It's in the latest release, 3.3 :)
