### ISSUE TITLE
Not working on iOS devices.

### ISSUE THREAD

**Issue by DejanBelic** [qodesmith/datepicker#36]
On Android it works perfectly, but on any ios devices, it doesn't work at all... Was inspecting in browserstuck but there is no error or anything it just not trigger or instanciated datepicker I guess. Any ideas?

**Comment by qodesmith** [comment]
I've been meaning to getting around to testing this on my wife's iPhone. You're not the only one to point out [issues](https://github.com/qodesmith/datepicker/issues/33) with the iPhone, so it's definitely valid. I'll look into this hopefully in the next day or two and have some insight.

**Comment by DejanBelic** [comment]
This is the fastest response in the history of a web for sure. Thank you for pointing that out, I've missed it. Also as I've written It doesn't trigger at all instance, though I've added click event on the instance and it triggers the calendar and opens it, nothing works it can't be closed selected or anything.

**Comment by qodesmith** [comment]
Haha, thanks. This is definitely weird for sure. I don't have an iPhone so I can't even play around with it until I get home and use my wife's. I'm very interested in the why behind all of this. I'll keep you posted and hopefully I have a fix real soon!

**Comment by DejanBelic** [comment]
Thank you! Hope you'll solve this :)

**Comment by qodesmith** [comment]
Ok, it's been waaaaay too long, but I finally got my hands on an old iPhone 5s. Looks like Safari doesn't like responding to click events for non-traditional-clicky elements - i.e. those that aren't a <a>, <button>, blah blah blah. I just tried testing with `touchstart` and it works. Let me see what I can come up with...

**Comment by qodesmith** [comment]
You guys aren't going to believe this... According to my experiments, it was all because I was attaching my listeners to the `window` and not the `document`. You can see it on [this line](https://github.com/qodesmith/datepicker/blob/master/datepicker.js#L161). I'm at the tail end of a new version of the library that refines a lot of the internals and gives some new instance methods to enable you to create a date-_range_ picker. That work is being done on the [two-instances](https://github.com/qodesmith/datepicker/tree/two-instances) branch and is almost done. I've just started writing some tests. Once that's done, I'll push, and this will aaallllll go away. Stay tuned...

**Comment by qodesmith** [comment]
I've pushed a fix to the master branch for iOS folks. Happy datepicking!

**Comment by deepakmchetu** [comment]
This issue has been closed for long, but I am facing it right now on iOS devices. I am on version 5.16.0.

Is there any additional parameter or hack I need to use?

```
    let picker = datepicker('#datepicker', {
      minDate: minDate,
      maxDate: maxDate,
      disabler: date => date.getDay() === 0,
      onSelect: (instance, date) => {
        // some processing on selection
      }
    });
```

It seems fine, right?

**Comment by qodesmith** [comment]
@deepakmchetu I just tried on an iPhone 11 and it seems to be working fine. See the video attached. What exactly is happening for you? Can you share a video or screenshot? The code you posted above looks fine to me. For testing purposes, try removing `onSelect` and use the default behavior and see if you're still having issues.

https://user-images.githubusercontent.com/11034792/103412672-545a5e80-4b44-11eb-9df9-ca3b44974358.MP4

**Comment by deepakmchetu** [comment]
I am testing it on BrowserStack, it has also been reported to me with testing on an actual iPad.

Please be patient when you look at the video, I only had a single minute to test this on a free account, so started the recording first. In the video, I am trying to trigger the calendar by clicking on the calendar icon. It works on desktop and Android, not on iOS.

Here's the video, https://www.loom.com/share/22ba7d75407f4f0098fb08c1c7da3314

https://user-images.githubusercontent.com/63185212/103460957-b089d200-4d40-11eb-9ec7-d4cbce74159b.mp4

**Comment by qodesmith** [comment]
@deepakmchetu Can you share the actual code? I'm guessing this has more to do with the icon and touch events not passing through rather than datepicker itself. I just tried on an iPad pro and it's working:

https://user-images.githubusercontent.com/11034792/103461206-a937d980-4cea-11eb-8e60-d13a4476f2e7.MP4

**Comment by deepakmchetu** [comment]
**Markup:**
---------

```html
            <div class="checkout-form">
              <label>Select Preferred Delivery Date:
                <span class="forklift">Forklift included</span>
              </label>
              <div class="city-state-form city-state-form1">
                <form class="form">
                  <div class="form-group" id="preferred-date">
                    <input type="text" id="month" placeholder="month" readonly="readonly" class="input-field" style="width: 49%;display: inline-block;">
                    <input type="text" id="day" placeholder="day" readonly="readonly" class="input-field" style="width: 49%;display: inline-block;">
                    <i class="fas fa-calendar-day" id="datepicker"></i>
                  </div>
                </form>
              </div>
            </div>
```

**JavaScript:**
-----------

```js
initiateDatepicker() {
    let $this = this;
    
    // map month number to name
    const monthName = {
      0: 'January',
      1: 'February',
      2: 'March',
      3: 'April',
      4: 'May',
      5: 'June',
      6: 'July',
      7: 'August',
      8: 'September',
      9: 'October',
      10: 'November',
      11: 'December'
    }
    
    // compute the min and max date
    let minDate;
    let maxDate;
    
    let date = new Date();
    date.setTime(date.getTime() + date.getTimezoneOffset()*60*1000);
    
    let estDate;
    let estOffset = -300;
    estDate = new Date(date.getTime() + estOffset*60*1000);
    if (
      (estDate.getHours() > 9) ||
      (estDate.getHours() === 9 && estDate.getMinutes() > 0) ||
      (estDate.getHours() === 9 && estDate.getSeconds() > 0)
    ) {
      minDate = new Date(estDate.getTime() + 24*60*60*1000);
    } else {
      minDate = estDate;
    }
    
    // check if the min date is a Sunday and adjust accordingly
    if (minDate.getDay() === 0) {
      minDate = new Date(minDate.getTime() + 24*60*60*1000);
    }
    
    // set max date to +14 of the min date
    maxDate = new Date(minDate.getTime() + 14*24*60*60*1000);
    
    // initiate datepicker with option parameters
    let picker = datepicker('#datepicker', {
      minDate: minDate,
      maxDate: maxDate,
      disabler: date => date.getDay() === 0,
      onSelect: (instance, date) => {
        document.querySelector('#day').value = date.getDate() > 9 ? date.getDate() : `0${date.getDate()}`;
        document.querySelector('#month').value = monthName[date.getMonth()];
        
        let now = new Date();
        now.setTime(now.getTime() + now.getTimezoneOffset()*60*1000);
        now = new Date(now.getTime() + estOffset*60*1000);
        
        let hours = now.getHours();
        let minutes = now.getMinutes();
        let seconds = now.getSeconds();
        let ampm = 'AM';
        if (hours > 12) {
          ampm = 'PM'
        } else if (hours === 12 && minutes > 0) {
          ampm = 'PM';
        } else if (hours === 12 && minutes === 0 && seconds >= 0) {
          ampm = 'PM';
        }
        hours = hours === 0 ? 12: hours % 12;
        
        let preferredDate = `${monthName[date.getMonth()]} ${date.getDate()
        }, ${date.getFullYear()} ${hours > 9 ? hours : `0${hours}`}:${minutes > 9 ? minutes : `0${minutes}`
        }:${seconds > 9 ? seconds : `0${seconds}`} ${ampm}`;
        let preferredRequestDate = `${date.getMonth() < 9 ? `0${date.getMonth() + 1}` : date.getMonth() + 1
        }/${date.getDate() < 10 ? `0${date.getDate()}` : date.getDate()}/${date.getFullYear()}`;
        
        instance.el.dataset.date = preferredDate;
        instance.el.dataset.requestDate = preferredDate;
        let deliveryRequest = JSON.parse($this.elements.deliveryOptions.dataset.deliveryRequest);
        deliveryRequest.delivery_date = preferredRequestDate;
        $this.elements.deliveryOptions.dataset.deliveryRequest = JSON.stringify(deliveryRequest);
        
        // set data in the order comments
        $this.commentsJSON.preferred_date = preferredDate;
        $this.service.updateCheckout({
          customerMessage: JSON.stringify($this.commentsJSON)
        });
        
        $this.validateShipping();
      }
    });
  }
  
  this.initiateDatepicker();
```

**Comment by qodesmith** [comment]
@deepakmchetu Ok, I see you're using font awesome. I just spun up a sample project using font awesome with the html you gave me. It worked on Android, iPhone, and the iPad. _However_... the `<i class="fas fa-calendar-day" id="datepicker"></i>` is a little sketchy because of its size. I had to increase the padding on it to 10px in order for it work for me. Try doing something obnoxious... add like 30px padding to the `i` element and see if it works for you. That will at least confirm that datepicker is working. I think at the end of the day you'll have to experiment with whatever CSS works for you. Let me know what happens.

**Comment by qodesmith** [comment]
@deepakmchetu You're very welcome! Happy coding my friend :)
