### ISSUE TITLE
Incorrect current date

### ISSUE THREAD

**Issue by Rafferty97** [qodesmith/datepicker#38]
I've just implemented datepicker on a form, but it appears to be highlighting August 23 as today's date, as opposed to July 23 as it should. An off-by-one error?

**Comment by qodesmith** [comment]
@Rafferty97 I just tried and everything looks fine to me. Can you post your code?

**Comment by Rafferty97** [comment]
@qodesmith 

I think I've worked out the source of the error. It's because I live in the timezone GMT+8.

In the `createMonth` function, whether or not it is today's month is determined by comparing `today.toJSON().slice(0, 7)` to `date.toJSON().slice(0, 7)`. However, when `date` is serialized to JSON, it is also converted to GMT. Hence, on my browser `date.toJSON()` renders as `"2018-06-30T16:00:00.000Z"` when the selected month is July, which is then interpreted as June.

**Comment by qodesmith** [comment]
Excellent find. I've just merged, rebuilt, & republished to npm. We're good to go!
