### ISSUE TITLE
Feature Request: Option to disable datepicker on touch-enabled devices 

### ISSUE THREAD

**Issue by pryley** [qodesmith/datepicker#4]
This is how I do it, but it would be handy as an option.

```js
var startDate = document.querySelector('#start-date');
var endDate = document.querySelector('#end-date');
var onEv = (type, el, handler) => el.addEventListener(type, handler, false);

if('ontouchstart' in window) {
    // Device is touch-enabled so change the input type to "date" in order to get the date keyboard
    [startDate, endDate].forEach(function(el) {
        onEv('touchstart', el, (ev) => ev.target.type = 'date');
        onEv('focusout', el, (ev) => ev.target.value || (ev.target.type = 'text'));
    });
}
else {
    // Device is not touch-enabled so we load the datepicker
    var dateStart = startDate && datepicker('#start-date');
    var dateEnd = endDate && datepicker('#end-date');
}
```

Here we are using the native date keyboard instead of the datepicker on a touch-enabled device:

![img_5573](https://cloud.githubusercontent.com/assets/134939/24822877/cd6604ca-1bc6-11e7-9e78-f770b131c3e6.png)

**Comment by qodesmith** [comment]
Looking into this now...

**Comment by qodesmith** [comment]
You can now pass `disableMobile: true` into the options. Datepicker will then not show on mobile devices. The input type has to be "date": `<input type="date">`.

Keep in mind, date inputs will not let Datepicker visibly populate the input field with a date. Using Datepicker on a date input field will still retain the chosen date on the Datepicker instance, but won't visibly show on the screen. You would have to implement logic to change the input's type based on mobile / non-mobile.
