### ISSUE TITLE
Bug / Enhancement: Multiple Datepicker on a page, with one invocation

### ISSUE THREAD

**Issue by Abourass** [qodesmith/datepicker#41]
I'm using the class .fancyDatePicker (as I prefer yours over the one included in Materialize-CSS, and theirs already uses datepicker), and when you make multiple instances on a page only the first one works. The rest perform no action on being clicked. I realise I could make multiple invocation for each instance, but it'd be nice if they'd all work with the single invocation. 

## Context
I'm making an app with express/node that's largely around CMA's (Comparative Market Analysis), so it's really common to have stuff like Sale Date, Date Listed, etc. Currently looking at a form with 8 instances of .fancyDatePicker.

## Your Environment
* Version used: Most Recent
* Browser Name and version: Chrome, Most Recent
* Operating System: Windows 7

**Comment by qodesmith** [comment]
I think this is a duplicate issue. See my comments on the [other ticket](https://github.com/qodesmith/datepicker/issues/42) you raised.
