### ISSUE TITLE
Manual date input

### ISSUE THREAD

**Issue by patrikrazem** [qodesmith/datepicker#47]
Maybe this is actually a feature and I just don't understand the point of it, but why is manual typing of the date prevented? More specifically, why is the manual input limited to 4 numbers?

I can see this making sense in the custom "Year" input, but why not have the ability to let the user enter a custom date in the field?

**Comment by qodesmith** [comment]
@patrikrazem You just found a bug :)  This behavior was mistakenly applied to *all* inputs on the page whereas my intention was to only apply it to the year overlay input. I'll whip up a fix. Thanks for pointing this out.

**Comment by qodesmith** [comment]
Ok, the fix is up. Let me know if there's still a problem.

**Comment by patrikrazem** [comment]
Just updated the npm module and it works as expected. Thanks - that was quick :)
