### ISSUE TITLE
Date format?

### ISSUE THREAD

**Issue by MACscr** [qodesmith/datepicker#5]
Am I blind? I dont see where to set the date format.

**Comment by qodesmith** [comment]
You're not blind. Currently there's no option to set the date format. I can add that as a feature. In the meantime, if you'd like to change it yourself, the input field is populated with a date inside the `setElValues` function. Right now its just using the `.toDateString()` method on a JavaScript date object.

**Comment by qodesmith** [comment]
@MACscr By the way, I've added the `formatter` option for users to provide a custom function which will set the value of the `<input>` element any way you want. I've also updated the README to give an example usage. Hope that helps!
