### ISSUE TITLE
Feature Request: Month Selector

### ISSUE THREAD

**Issue by Abourass** [qodesmith/datepicker#50]
Hello again! 
Been using your datepicker's in our app for a bit now, and I absolutely love them. The only thing I'm asked consistently is if there is a way to change the overlay behavior so that once you type in a year, you are next shown the months, click your month, now shown the dates for that month. This would solve users that are in December having to click the arrow 12 times to get to December. Is something like that feasible?

**Comment by qodesmith** [comment]
That's a great feature request. I think that makes a better user experience / workflow for this calendar. Stay tuned...

**Comment by qodesmith** [comment]
@Abourass I know it's been a while, but just wanted you to know that I'm working on this as we speak :)

**Comment by Abourass** [comment]
Awesome! Extremely glad to hear that :+1: :smile:

**Comment by qodesmith** [comment]
@Abourass Aaaaaaand we're done. The [customOverlayMonths](https://github.com/qodesmith/datepicker#customoverlaymonths) feature has been happily implemented 😎

**Comment by qodesmith** [comment]
To be clear, the months list is now a permanent feature of the overlay. You also have the ability to customize it if you'd like. But navigating months by clicking the arrows isn't your only option anymore. Thanks for suggesting this feature!
