### ISSUE TITLE
Babel preset-env removal breaks compatibility with IE

### ISSUE THREAD

**Issue by pawelgabryelewicz** [qodesmith/datepicker#51]
Hi, in 4.0.10 you have removed babel preset-env from your webpack config claiming that it's no longer used. In fact it was - compare your minified builds from `dist` between 4.0.9 and 4.0.10. The latter doesn't work on IE because arrow functions appeared in the compiled code (that should be ES5-compatible). I think you should bring it back (and by the way switch to a different building tool such as `rollup` - `webpack` seems to be an overkill there).

**Comment by qodesmith** [comment]
You're absolutely right. I was trying to iron out webpack and IE issues a few months ago but put it down because things got busy over here. I'll try to resolve it soon.

**Comment by qodesmith** [comment]
Just settled down in a new job so I'll be taking another look at this. Going to use Browserstack to emulate older versions of IE to iron out the kinks. I plan on finalizing the Webpack config.

**Comment by qodesmith** [comment]
@pawelgabryelewicz Just updated the library. Babel's preset-env has been reintroduced.
