### ISSUE TITLE
Readonly field trigger click event

### ISSUE THREAD

**Issue by cebindani** [qodesmith/datepicker#54]
We have a following problem: set a input as disabled does accessibility ignores the field. To avoid this, I set input field as readonly, but click event still open datepicker.
That's a way to remove a click listener by demand, without remove datepickers instance?

**Comment by qodesmith** [comment]
Thanks for your patience. Just settled down in a new job so I'll be spending some time on resolving bugs.

**Comment by qodesmith** [comment]
Hey @cebindani, I'm not sure I understand. Are you saying that when you set an input to disabled - `<input disabled />` - that you want to make sure the calendar doesn't open?

**Comment by cebindani** [comment]
The problem is when I set input as `readonly` the calendar should not open.

**Comment by qodesmith** [comment]
Ahhh, I see what you're saying. Ok, let me look into this.

**Comment by qodesmith** [comment]
@cebindani Done! The new feature you'll want to use is [respectDisabledReadOnly](https://github.com/qodesmith/datepicker#respectdisabledreadonly). Set it to `true` and you should be good to go.

**Comment by qodesmith** [comment]
Correction... the calendar opens, but it is unable to select a date or change the value of the input. Hence the `readonly` part.

**Comment by qodesmith** [comment]
UPDATE: I just added the [disabled](https://github.com/qodesmith/datepicker#disabled) feature. Feel free to use that as well.
