### ISSUE TITLE
WCAG 2.0 Accessibility coverage.

### ISSUE THREAD

**Issue by aharris** [qodesmith/datepicker#55]
The following issues presented themselves when running this through an accessibility tool:

![image](https://user-images.githubusercontent.com/713398/57643990-17191580-7589-11e9-9a0e-74f9811ebe8e.png)

Is it possible to get `aria-label`s applied to these elements?

**Comment by cebindani** [comment]
@aharris A person with disability it's not capable to using a datepicker. Most recommended in this case is to able manual input in datepicker field.
In my project, we put aria-hidden in both datepicker container and input.qs-overlay-year to avoid accessibility issues.

**Comment by qodesmith** [comment]
This library doesn't create the `<input />` element, so it's up to you to add the attributes. You're free to apply whatever attributes you want.

**Comment by aharris** [comment]
@qodesmith. If you look at the screenshot above that element is coming from your library not the parent element. After closer review of this library I also discovered it is not keyboard accessible which makes any other accessibility's fairly null and void. This seems like a nice library but without accessibility for all users I had to go a different route.

**Comment by qodesmith** [comment]
Ooooo, I see. You're not talking about the input that the calendar attaches to, rather, the input for the year. Sorry about that. It would be pretty easy to expose an option that lets you put whatever attributes you want on the year overlay input.
