### ISSUE TITLE
ReferenceError: Cannot access 'datepicker' before initialization

### ISSUE THREAD

**Issue by TrejoCode** [qodesmith/datepicker#57]
I used in React, when set a State to true

ReferenceError: Cannot access 'datepicker' before initialization

My code:
 const datepicker = datepicker('#birthDay');

**Comment by qodesmith** [comment]
Not that you should be using this library with React, but I just tried it and it worked perfectly fine. Here's an example component using hooks:

```javascript
import React, { useEffect } from 'react'
import datepicker from 'js-datepicker'

const Home = () => {
  useEffect(() => {
    datepicker('#test')
  }, [])

  return <input type="text" id="test" />
}
```
