### ISSUE TITLE
Date input type

### ISSUE THREAD

**Issue by MACscr** [qodesmith/datepicker#6]
It doesnt appear to work with `<input type="date">`

**Comment by qodesmith** [comment]
So `date` input's are a fickle beast. They are trying to do some of the work for you out of the box, which messes things up with datepicker. I meant to update the readme file to indicate this, so I'll do that soon. `date` input's want to display their own date only if you use the built-in calendar they provide. I suggest using `<input type="text">` instead. But even with the `date` input, when selecting a day off the datepicker calendar, the instance will indeed update with the selected date.
