### ISSUE TITLE
Datepicker opens on init ver 5.0.0

### ISSUE THREAD

**Issue by yan-010** [qodesmith/datepicker#61]
After updating to the new 5.0.0, after the datepicker component is created first time on init it opens automatically.

datepicker.hide() is not working for the first time on init, then works normally

**Comment by Abourass** [comment]
Same here

**Comment by qodesmith** [comment]
O no! Ok, let me look into this.

**Comment by qodesmith** [comment]
@yan-010 @Abourass Fixed now in 5.0.1. Thanks for bringing this to my attention!
