### ISSUE TITLE
5.0.1 => auto open and style problem

### ISSUE THREAD

**Issue by yan-010** [qodesmith/datepicker#63]
After updating to 5.0.1 the datepicker is automatically opened on init and also there is a style problem, picture attached

![image](https://user-images.githubusercontent.com/54237993/63348880-de948f00-c362-11e9-9831-61bb79d96761.png)

**Comment by qodesmith** [comment]
I just spun up a new test project, installed datepicker 5.0.1, and everything is working as expected. How are you importing the datepicker styles? And perhaps you need to clear cache to ensure the js for datepicker isn't stale.

**Comment by yan-010** [comment]
5.0.2 working good, thank you
