### ISSUE TITLE
I need a tutorial for installing datespicker in the Express-handlebars template engine.

### ISSUE THREAD

**Issue by osvaldodelr** [qodesmith/datepicker#65]
You could publish a written or video tutorial with the detailed step by step of how to install and configure the js-datespicker module in nodejs and express-handlebars, I would like to be able to use this component, but the documentation is not oriented to express-handlebars and already  I do not know what to do to make it work, you need me to send you images of my code just let me know I am attentive to your response.

**Comment by qodesmith** [comment]
Hey @osvaldodelr. That's a bit out of the scope of a github issue, but maybe a I can shed a little light on your current setup.

For one, using express-handlebars has no effect on installing this library. [Installation](https://github.com/qodesmith/datepicker#installation) remains the same - `npm install js-datepicker` if you're using npm or just include `<script src="https://unpkg.com/js-datepicker"></script>` in your index.html file. Don't forget about the css also. Refer to the [installation instructions](https://github.com/qodesmith/datepicker#installation).

As far as using this library in your code, I don't think the handlebars stuff affects that either - I'm not sure. Where is your client-side JavaScript? Meaning, where is the JavaScript code for your site? That's where the datepicker usage would go. Every situation looks a bit different, but using this library is not really that much different than using any other library - it lives in your client side code.
