### ISSUE TITLE
.toDateString()

### ISSUE THREAD

**Issue by 0000marcell** [qodesmith/datepicker#66]
in the function setCalendarInputValue, toDateString is returning a date in other language other than the computer language on chrome 77.038, so when we select a date the date is in the wrong language

**Comment by 0000marcell** [comment]
Maybe we could have a option to set the locale in the selected date
```
function setCalendarInputValue(el, instance, deselect) {
  if (instance.nonInput) return
  if (deselect) return el.value = ''
  if (instance.formatter !== noop) return instance.formatter(el, instance.dateSelected, instance)
  // new code
  el.value = new Intl.DateTimeFormat(<<<<language option here >>>>>>>>>).format(instance.dateSelected);
  // old code
  //el.value = instance.dateSelected.toDateString()
}
```

**Comment by qodesmith** [comment]
The usage of `toDateString` is the default option. What you'd want to do in your case is provide a custom [formatter](https://github.com/qodesmith/datepicker#formatter) option so you can format the date however you'd like.

**Comment by qodesmith** [comment]
So for example, you would do something like this:

```javascript
const picker = datepicker('.my-class', {
  formatter: (input, date, instance) => {
    input.value = new Intl.DateTimeFormat(YOUR_LOCALE, OPTIONS) // https://mzl.la/2lkBDlt
      .format(instance.dateSelected); // https://mzl.la/2mWwpfV
  }
})
```

**Comment by 0000marcell** [comment]
Thx, didn't notice this option in the documentation, gonna close
