### ISSUE TITLE
onSelect not being fired

### ISSUE THREAD

**Issue by Arcath** [qodesmith/datepicker#7]
I'm trying to use the date picker with [etch](https://github.com/atom/etch) and its not firing the `onSelect` event.

My code looks like this:

```javascript
    datePicker(this.refs.input, {
      dateSelected: new Date(this.value),
      onSelect: function(){
        console.dir('selected')
      },
      onShow: function(){
        console.log('show')
      },
      onHide: function(){
        console.log('hide')
      }
    })
``` 

If I watch the console `show` and `hide` get logged but onSelect does not. It also doesn't update the input with new value.

**Comment by qodesmith** [comment]
I'm unable to reproduce this. `onSelect` is working on this end. What version of datpicker are you using?

**Comment by Arcath** [comment]
`this.refs.input` is an input box. It gets its date set correctly in there and clicking it brings up the date selector (triggering `onShow`). The date selector is fully interactive but when I click on a date it doesn't update anything, but it does trigger `onHide` and disappears.

I shouldn't be because I'm using Etch to render the input as it opens normally and no updating has occurred yet. It could be because Atom is interacting with the events but I'm not sure.

I just wanted to check I wasn't missing something with that code.

**Comment by qodesmith** [comment]
Yea, wish I could see the rest of your code and understand exactly what's going on. But you're correct. You're using datepicker correctly. If you want to tamper under the hood yourself, the onSelect function you provide is fired in the `selectDay` function. Maybe throw some `console.log`'s in there to see what's going on. Let me know if I can help further.
