### ISSUE TITLE
All clicks inside the DatePicker are bubbling to parent

### ISSUE THREAD

**Issue by CSIDev-CMF** [qodesmith/datepicker#74]
I've got a situation where a wrapper div is listening for all clicks inside it, to then perform a JS "click" into the input box. 

This is typical UX for something like a checkbox, click the label and the checkbox is selected.

Our problem is we need to tell all clicks inside the datepicker (month selector/navigator) to withhold it's clicks and not allow them to bubble up to parent elements outside date picker.

Result:
- Our Input box originally has an Onclick=toggleDatePicker
- As it is, that is working perfect, we are stopping propogation there
- But, a click inside the datepicker fires a "click to the input" via a parent control
- The result is that this fires: Onclick=toggleDatePicker

Question:
- Are there any settings to tell OnClick of datepicker to stoppropogation?  If not, suggestion on how to re-write all onclick events inside the datepicker to stop the bubbling effect?

**Comment by qodesmith** [comment]
Sorry for the delayed response. I'm currently working on finishing up writing tests with Cypress. Once that's done, I'll come back around to this.

**Comment by qodesmith** [comment]
Hi @CSIDev-CMF. Sorry for the delay here. FYI, the newest version 5.3.0 is out, which includes a re-write in ES5 syntax - better support for older browsers.

For your issue, perhaps you could check in your onclick handler if the event originated from the datepicker. I'd imagine something like this:

```javascript
function onClickHandler(e) {
  const calendarContainer = document.querySelector('.qs-datepicker-container')

  if (calendarContainer.includes(e.currentTarget)) return

  // The rest of your logic here...
}
```

Would that solve the issue for you?

**Comment by qodesmith** [comment]
Closing this. Let me know if it's still an issue.
