### ISSUE TITLE
date range: move end range calendar display month to the one selected in start range

### ISSUE THREAD

**Issue by sfusato** [qodesmith/datepicker#75]
When using the datepicker in "range" mode, if you select a date from the future, say June 2020, in the `start` range calendar, the `end` range calendar will still display with current month when opened even though all the dates up to June 2020 are disabled.

Instead, it should open with June 2020 (as in my example) and save the user a few clicks.

**Comment by qodesmith** [comment]
Good catch. I'm currently working on adding Cypress testing to this library, so as soon as that's done I'll get this going. I agree this should be the user experience.

**Comment by qodesmith** [comment]
@sfusato This is now available in 5.4.0!

**Comment by sfusato** [comment]
Awesome. Thank you!

Can you push 5.4.0 also to NPM? Thanks.

**Comment by qodesmith** [comment]
Oops! Just pushed :)
