### ISSUE TITLE
IE11 datepicker issue

### ISSUE THREAD

**Issue by gianlucalarizza** [qodesmith/datepicker#76]
Hello,
in Ie11 the script doesn't work.
In console we have : Syntax error --> datepicker.min.js (466,1)

Are you going to support it?
Many thanks for your work

**Comment by qodesmith** [comment]
I'm working on a branch to add testing, and in that branch I've re-written then entire library to be es5 compliant. When I'm done, it should work well with IE11 and even further back. Stay tuned...

**Comment by qodesmith** [comment]
@gianlucalarizza Version 5.3.0 is out. It's been totally re-written in ES5 syntax. Try that version and let me know if there's still issues!

**Comment by gianlucalarizza** [comment]
Hi @qodesmith , it work correctly. Many thanks for your good job. Cheers!
