### ISSUE TITLE
remove() function

### ISSUE THREAD

**Issue by Saconov** [qodesmith/datepicker#78]
When using the remove function of any datepicker, the following error occurs:

datepicker.min.js:4 Uncaught (in promise) ReferenceError: **prop** is not defined
    at Object.N [as remove] (datepicker.min.js:4)

However, declaring the prob variable within the datepicker.min.js file fixed this issue for me.
`for(**let** prop in n.remove()`
or in datepicker.js
`for (**let** prop in this) delete this[prop]`.

Seems like somehow the prop variable was not declared.

**Comment by qodesmith** [comment]
Ahhh, good catch. I'll put up a fix.

**Comment by qodesmith** [comment]
Done! Version 5.5.0 is out now.
