### ISSUE TITLE
When clicking the start date in the second calendar the date is deselected

### ISSUE THREAD

**Issue by d2roth** [qodesmith/datepicker#80]
I found a bug when selecting the end date to be the same as the start date. Essentially when you select the end date after the start date and then change it to the same as the start date the end date is unset.

Steps to reproduce:
2. Select Date 1
3. Select Date 2 after Date 1
4. Select Date 2 the same as date 1
5. Notice that the end date input field is cleared

Expected results:
The date range should be from date 1 to date 1.

You can see my setup here:
https://codepen.io/Daniel-Roth/pen/RwPBodB

**Comment by qodesmith** [comment]
Very interesting. Yup, I was able to reproduce this. I'll take a look.

**Comment by qodesmith** [comment]
5.5.1 is out with the fix. Good catch.
