### ISSUE TITLE
[Feature]: allow to enable days added by showalldates option

### ISSUE THREAD

**Issue by KillerCodeMonkey** [qodesmith/datepicker#85]
The option `showAllDates` shows day overlaps with the previous and next month. It would be nice to have the ability to activate them as every other day in the current month.

https://www.npmjs.com/package/js-datepicker#showalldates

**Comment by qodesmith** [comment]
Working on this now...

**Comment by qodesmith** [comment]
@KillerCodeMonkey This is now available in 5.13.0.

**Comment by KillerCodeMonkey** [comment]
Nice :). Thanks

Aaron Cordova <notifications@github.com> schrieb am Fr., 22. Mai 2020,
15:28:
