### ISSUE TITLE
tabindex for input input.qs-overlay-year

### ISSUE THREAD

**Issue by lapagept** [qodesmith/datepicker#87]
Thanks for your great script.

I had a problem with input element of the year.

This input had tabIndex value = 0.

It breaks my navigation with "tab" key in my project.

So, I had to put this line in "onShow" event callback : 
        document.getElementsByClassName("qs-overlay-year")[0].tabIndex = -1;

May be you could do something for this.

Thanks

**Comment by qodesmith** [comment]
The code doesn't set a tab index for the year input within the overlay:

<img width="478" alt="Screen Shot 2020-04-22 at 5 30 22 PM" src="https://user-images.githubusercontent.com/11034792/80036037-07a38b80-84bf-11ea-8404-b934aeaf2781.png">

**Comment by qodesmith** [comment]
Perhaps the browser assigns a default value of 0 if none is specified.
