### ISSUE TITLE
Navigation is not working

### ISSUE THREAD

**Issue by cargarn** [qodesmith/datepicker#92]
I am trying to use "navigate" function, and it is failing:

picker.navigate(new Date(2020, 3, 3));

I got this error: ReferenceError: date is not defined

**Comment by qodesmith** [comment]
I'm unable to reproduce this. Can you share the full datepicker setup you've got going?

**Comment by qodesmith** [comment]
@cargarn Actually, you were right! Turns out I mistakenly had set `date` as a global variable inside the `navigate` function. So in environments using `'use strict'`, that would cause the error. This is fixed in 5.12.0. Thanks for the catch!
