### ISSUE TITLE
Object doesn't support property or method 'getRootNode'

### ISSUE THREAD

**Issue by iammugik** [qodesmith/datepicker#93]
Datepicker not initialize in IE11 with error:
Object doesn't support property or method 'getRootNode'
Can you check please?

**Comment by qodesmith** [comment]
@iammugik I think I see what's happening. Since this library supports usage with a shadow dom, I'm doing a check with `getRootNode` to determine wether or not we're in a shadow dom. This doesn't work with IE. I'll get a fix together.

**Comment by iammugik** [comment]
@qodesmith great, thanks!

**Comment by qodesmith** [comment]
@iammugik Ok, a fix has been pushed. Can you upgrade to 5.13.0 and tell me if it works for you now?

**Comment by iammugik** [comment]
@qodesmith yes, it works! thank you for quick fix :)
